### ISSUE TITLE
White background changed to black after clicking on buttons Cancel or Finish

### ISSUE THREAD

**Issue by code81** [Surnet/ionic-multi-camera#4]
Original white background changed to black after closing camera with buttons Cancel or Finish.

Android 7.0
Ionic 3.20.0
Cordova 8.0.0
Application created by: ionic start multi-camera sidemenu
I have made all tasks from your README.

[Screenshot before](https://drive.google.com/file/d/1HNATK7UTCzydzklYHahD9Je9ba7inpv-/view)
[Screenshot after](https://drive.google.com/file/d/1LA6TTGnfQDxrYPmB0f66bxwI4LyVyG9D/view)

**Comment by dhavalsharma387** [comment]
I have resolved this issue with ionic dynamic theme logic.

**Comment by sheyabernstein** [comment]
@dhavalsharma387 could you please elaborate?
