### ISSUE TITLE
Camera continues capturing and showing output in background after clicking on Back button

### ISSUE THREAD

**Issue by code81** [Surnet/ionic-multi-camera#5]
Camera continues capturing and showing output in background after clicking on Back button in Android.

Android 7.0
Ionic 3.20.0
Cordova 8.0.0
Application created by: ionic start multi-camera sidemenu
I have made all tasks from your README.

[Screenshot before](https://drive.google.com/file/d/1HNATK7UTCzydzklYHahD9Je9ba7inpv-/view)
[Screenshot after](https://drive.google.com/file/d/12kc3zGOLxpwsGjhFm4UNgMzhFWb_88Ld/view)

**Comment by dhavalsharma387** [comment]
I have resolved this issue with ionic dynamic theme logic and handling back button pressed.
