### ISSUE TITLE
Not work in ios 

### ISSUE THREAD

**Issue by ashishvadhwa** [Surnet/ionic-multi-camera#6]
When i use this with ios device it takes more time to display image preview and after capturing two images it display white screen  and app will not work more

**Comment by chdanielmueller** [comment]
Hi @ashishvadhwa,
I do no longer maintain this code. Feel free to use it and try to fix the error yourself.
Sorry that I do not have better news.

**Comment by ashishvadhwa** [comment]
Ok thanks i will try.
Thanks for your response
